### ISSUE TITLE
Links to "Real-time Change Data Capture" and "Streaming Query Replication" point to localhost

### ISSUE THREAD

**Issue by kroy** [PeerDB-io/docs#39]
On the [`commands/supported-connectors` page](https://docs.peerdb.io/sql/commands/supported-connectors), two links point to localhost: https://github.com/PeerDB-io/docs/blob/main/sql/commands/supported-connectors.mdx

Exciting project!

**Comment by iskakaushik** [comment]
Thanks for the issue, this should be fixed now!
